In [1]:
import gensim.downloader as api
import pandas as pd

GAMES_DATA = "../data/clean_data.csv"
w2v_model = api.load('word2vec-google-news-300')
games_data = pd.read_csv(GAMES_DATA, sep=";")
games_data

,Name,Release date,Estimated owners,About the game,Positive,Negative,Developers,Publishers,Categories,Genres,Tags,Popularity
0,Counter-Strike: Global Offensive,21.08.2012,100000000,Counter-Strike: Global Offensive (CS: GO) expa...,5764420,766677,"Valve,Hidden Path Entertainment",Valve,"Multi-player,Steam Achievements,Full controlle...","Action,Free to Play","FPS,Shooter,Multiplayer,Competitive,Action,Tea...",0.785569
1,Dota 2,09.07.2013,200000000,"The most-played game on Steam. Every day, mill...",1477153,300437,Valve,Valve,"Multi-player,Co-op,Steam Trading Cards,Steam W...","Action,Free to Play,Strategy","Free to Play,MOBA,Multiplayer,Strategy,e-sport...",0.566434
2,PUBG: BATTLEGROUNDS,21.12.2017,100000000,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",1154655,895978,"KRAFTON, Inc.","KRAFTON, Inc.","Multi-player,PvP,Online PvP,Stats,Remote Play ...","Action,Adventure,Free to Play,Massively Multip...","Survival,Shooter,Multiplayer,Battle Royale,FPS...",0.434255
3,Team Fortress 2,10.10.2007,100000000,The most fun you can have online - PC Gamer Is...,823693,56683,Valve,Valve,"Multi-player,Cross-Platform Multiplayer,Steam ...","Action,Free to Play","Free to Play,Hero Shooter,Multiplayer,FPS,Shoo...",0.275344
4,Black Myth: Wukong,19.08.2024,100000000,Black Myth: Wukong is an action RPG rooted in ...,663109,28700,Game Science,Game Science,"Single-player,Steam Achievements,Full controll...","Action,Adventure,RPG","Mythology,Action RPG,Action,RPG,Souls-like,Com...",0.257988
...,...,...,...,...,...,...,...,...,...,...,...,...
9574,Deserving Life,13.10.2017,100000,Deserving Life is a room-scale virtual reality...,96,20,"Lukas Paul, Gabriel Mittermair",Deserving Life,"Single-player,Steam Achievements",Free to Play,"Free to Play,Horror,VR",0.000211
9575,Timen runner,26.05.2017,100000,Hardcore pixel 2D platformer with steampunk el...,49,44,REX PEX GAMES,REX PEX GAMES,"Single-player,Steam Achievements,Steam Trading...","Casual,Indie","Indie,Casual,Platformer,2D,Pixel Graphics,Grea...",0.000211
9576,Mahjong Deluxe 2: Astral Planes,20.07.2016,100000,Mahjong Deluxe 2: Astral Planes is an out-of-t...,47,45,EnsenaSoft,EnsenaSoft,Unknown,Casual,"Casual,Puzzle",0.000211
9577,Pizza Frenzy Deluxe,30.08.2006,100000,Pizza Frenzy is a wacky action puzzler that pu...,125,5,"PopCap Games, Inc.","PopCap Games, Inc.",Single-player,Casual,Casual,0.000211
9578,Operation Breakout,28.10.2016,100000,Description Operation Breakout is a renewed mu...,35,51,"SGTTB_Studios,Phanom Games","SGTTB_Studios,Phanom Games","Multi-player,PvP,Online PvP,Shared/Split Scree...","Action,Adventure,Massively Multiplayer","Action,Massively Multiplayer,Adventure,FPS",0.000211

In [2]:
games_data['tags_token'] = games_data['Tags'].apply(lambda x: x.split(','))
games_data.tags_token

0       [FPS, Shooter, Multiplayer, Competitive, Actio...
1       [Free to Play, MOBA, Multiplayer, Strategy, e-...
2       [Survival, Shooter, Multiplayer, Battle Royale...
3       [Free to Play, Hero Shooter, Multiplayer, FPS,...
4       [Mythology, Action RPG, Action, RPG, Souls-lik...
                              ...
9574                           [Free to Play, Horror, VR]
9575    [Indie, Casual, Platformer, 2D, Pixel Graphics...
9576                                     [Casual, Puzzle]
9577                                             [Casual]
9578      [Action, Massively Multiplayer, Adventure, FPS]
Name: tags_token, Length: 9579, dtype: object

In [5]:
import numpy as np
def get_mean_embedding(tokens, model):
    embeddings = [model[word] for word in tokens if word in model]
    if embeddings:
        return np.mean(embeddings, axis=0)
    else:
        return np.zeros(model.vector_size)

games_data['tags_embd'] = games_data['tags_token'].apply(lambda x: get_mean_embedding(x, w2v_model))

In [6]:
games_data['tags_embd']

0       [0.14586464, -0.10756977, 0.0065800594, 0.0709...
1       [0.16716975, -0.20527788, 0.027969707, 0.04933...
2       [0.104766846, -0.15494792, 0.0029093425, 0.088...
3       [0.090799965, -0.0865682, -0.014912923, 0.1338...
4       [0.18888034, -0.124291055, -0.021447696, 0.009...
                              ...
9574    [0.15429688, -0.061706543, 0.07910156, 0.08712...
9575    [0.15161133, -0.1328125, -0.042877197, 0.09982...
9576    [0.17663574, -0.35253906, -0.12988281, 0.24853...
9577    [0.040771484, -0.41601562, -0.08203125, 0.1943...
9578    [0.11413574, -0.11930338, 0.10294596, 0.097941...
Name: tags_embd, Length: 9579, dtype: object

## check for 0 vectors in embedding

In [7]:
games_data[games_data['tags_embd'].apply(lambda x: np.all(x == 0))]

,Name,Release date,Estimated owners,About the game,Positive,Negative,Developers,Publishers,Categories,Genres,Tags,Popularity,tags_token,tags_embd
685,Gorilla Tag,12.02.2021,2000000,"Reject humanity. Run, climb, and jump in VR us...",17321,1123,Another Axiom,Another Axiom,"Multi-player,PvP,Online PvP,Cross-Platform Mul...","Action,Casual,Free to Play,Early Access","Early Access,VR Only",0.005574,"[Early Access, VR Only]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6006,Wakaru ver. beta,18.06.2018,200000,"Do you want to be a Vtuber, but have no VR dev...",320,37,えいえいっ! 怒った?,えいえいっ! 怒った?,Unknown,"Animation & Modeling,Video Production","Animation & Modeling,Video Production",0.000432,"[Animation & Modeling, Video Production]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6055,Ohm Studio,09.12.2013,200000,"Ohm Studio is the first real-time, pro-grade c...",164,103,GRAOUMF,Ohm Force,Unknown,"Audio Production,Software Training","Audio Production,Software Training",0.000429,"[Audio Production, Software Training]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6640,Ohmicide,23.07.2014,200000,Ohmicide:Melohman is an audio fx plugin which ...,1,0,Ohm Force,Ohm Force,Unknown,Audio Production,Audio Production,0.000400,[Audio Production],"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."